<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- Додаємо підтримку coverage -->
		<IsTestProject>true</IsTestProject>
		<CollectCoverage>true</CollectCoverage>
		<CoverletOutputFormat>opencover</CoverletOutputFormat>
		<CoverletOutput>../coverage/coverage.xml</CoverletOutput>
	</PropertyGroup>

	<ItemGroup>
		<!-- Тестові пакети -->
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.9.0" />
		<PackageReference Include="Moq" Version="4.20.69" />
		<PackageReference Include="NUnit" Version="3.14.0" />
		<PackageReference Include="NUnit3TestAdapter" Version="4.4.0" />

		<!-- Додаємо collector (важливо) -->
		<PackageReference Include="coverlet.collector" Version="3.2.0" />

		<!-- NetArchTest rules (твій ArchitectureTests.cs використовує їх) -->
		<PackageReference Include="NetArchTest.Rules" Version="1.3.2" />

	</ItemGroup>

	<ItemGroup>
		<!-- Лінкуємо основний проект -->
		<ProjectReference Include="..\NetSdrClientApp\NetSdrClientApp.csproj" />
	</ItemGroup>

</Project>
